default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
      args: ["--fix=lf"]
      exclude_types:
        - batch
    - id: name-tests-test
      args: ["--django"]
      exclude: tests/(factories|fixtures)
    - id: debug-statements
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: detect-private-key
    - id: check-executables-have-shebangs
    - id: check-builtin-literals
    - id: check-docstring-first
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: fix-byte-order-marker

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.22.3
    hooks:
    - id: toml-sort
      args: [--in-place, --all]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
        - --ignore=D100,D104,D105,D106,D107,D200,D203,D205,D212,D400
        exclude: |
          (?x)(
            migrations/.*
          )$
        additional_dependencies: [tomli]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports", "--in-place", "--recursive"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        additional_dependencies:
        - django-stubs
        args: ["--install-types"]


  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.2.1
    hooks:
      - id: flakeheaven
        additional_dependencies: [flake8-bugbear]
